name: C++ Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker
      run: docker build -t cpp-hello .

    - name: Run test
      run: docker run --rm cpp-hello